source :rubygems

gem 'squash'        , '= 0.0.5'

gem 'cucumber'      , '~> 0.10.0'
gem 'rspec'         , '~> 2.3.0'
#gem 'capybara'      , '~> 0.4.0'               # at the moment, version conflict with the capybara required by akephalos
gem 'akephalos'     , '~> 0.2.4'
gem 'syntax'        , '~> 1.0.0'      # Colored sintax in Cucumber's HTML output
