source :rubygems

gem 'cucumber'
gem 'rspec'
#  gem 'capybara'  # at the moment, version conflict with the capybara required by akephalos
gem 'akephalos'
gem 'syntax'       # Colored sintax in Cucumber's HTML output
#gem 'squash'
